### PR TITLE
V13and rebranding

### PR DESCRIPTION
**Pull request by johnSchnake**
*Description of changes:*
Includes changes regarding updated image lists, v1.13 Kubernetes, Ubuntu 18.04, and branding changes for VMware.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by johnSchnake** [comment]
@jaymccon my last PR here https://github.com/aws-quickstart/quickstart-vmware/pull/26 failed to pull in a foundation PR that further changed the instance list. If it is OK I would suggest just cutting off that merge and force pushing back to develop (like a hard rollback) and then putting these changes in their place.

The reason I say that is otherwise the develop branch is broken at this point in time and requires a custom commit that doesn't exist in our repos at all in order to make it functional.

If you'd rather I make the custom commit let me know.

**Comment by jaymccon** [comment]
hard resetting master to f2caa80bae0b6d5d6e2c238dca9b044d80d5f5d9

**Comment by jaymccon** [comment]
@johnSchnake can you just have a quick look at the new state of develop and confirm we're good to merge ?

**Comment by johnSchnake** [comment]
@jaymccon Will do; give me a few min to review and discuss.

**Comment by johnSchnake** [comment]
@jaymccon Looks good to us now; ready for this version to be merged to develop and tested.

**Pull request merged**
